2021-02-23 09:00:42

diff --git a/src/main/docker/Dockerfile b/src/main/docker/Dockerfile
--- a/src/main/docker/Dockerfile
+++ b/src/main/docker/Dockerfile
@@ -28,13 +28,13 @@ COPY --from=builder /tmp/dependencies/ ./
 COPY --from=builder /tmp/spring-boot-loader/ ./
 COPY --from=builder /tmp/snapshot-dependencies/ ./
 COPY --from=builder /tmp/application/ ./
-COPY --chown=root:root ./docker-entrypoint.sh /bin/docker-entrypoint.sh
+COPY --chown=root:root ./docker-entrypoint.sh /bin/entrypoint
 
-HEALTHCHECK --interval=10s --timeout=30s --start-period=3s --retries=3 CMD curl --fail http://localhost:8080/actuator/info || exit 1
+# HEALTHCHECK --interval=10s --timeout=30s --start-period=3s --retries=3 CMD curl --fail http://localhost:8080/actuator/info || exit 1
 
-RUN chmod +x /bin/docker-entrypoint.sh
+RUN chmod +x /bin/entrypoint
 
-ENV SPRING_PROFILES_ACTIVE=k8s
+ENV SPRING_PROFILES_ACTIVE=dev
 
 EXPOSE 8080
 
